name: Build macOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install LLVM & Ninja
        run: |
          brew install llvm
          brew list ninja &>/dev/null || brew install ninja
          echo "LLVM_PREFIX=$(brew --prefix llvm)" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_CXX_COMPILER=${{ env.LLVM_PREFIX }}/bin/clang++ \
            -DCMAKE_C_COMPILER=${{ env.LLVM_PREFIX }}/bin/clang \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=${{ env.LLVM_PREFIX }}/bin/ld64.lld" \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload binary
        uses: actions/upload-artifact@v4.6.2
        with:
          name: main-macos
          path: build/main
